default: &default
  encoding: unicode
  adapter: postgresql
  pool: 5

development:
  <<: *default
  host:     <%= ENV['POSTGRES_DATABASE_HOST'] %>
  port:     <%= ENV['POSTGRES_DATABASE_PORT'] %>
  database: <%= ENV['POSTGRES_DATABASE_NAME'] %>
  username: <%= ENV['POSTGRES_DATABASE_USERNAME'] %>
  password: <%= ENV['POSTGRES_DATABASE_PASSWORD']%>
  pool:     <%= ENV['POSTGRES_DATABASE_POOL'] %>